---
title: "Karten erstellen mit R"
author: "Jan-Philipp Kolb"
date: "11 Januar 2019"
output:
  beamer_presentation: 
    colortheme: beaver
    fonttheme: structurebold
    highlight: espresso
    keep_tex: yes
    fig_caption: no
    theme: CambridgeUS
  slidy_presentation: default
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r child = '/../../IntroR/buildingblocks/willkommen.Rmd'}
```

# Warum R?

```{r child = '/../../IntroR/buildingblocks/intror.Rmd'}
```

# Erste Schritte mit R

```{r child = '/../../IntroR/buildingblocks/erste_schritte_r.Rmd'}
```

# Hilfe bekommen

```{r child = '/../../IntroR/buildingblocks/hilfe_geomed.Rmd'}
```

# R ist modular

```{r child = '/../../IntroR/buildingblocks/rmodular.Rmd'}
```

# Warum die räumliche Perspektive

```{r child = '/../../IntroR/buildingblocks/geomotiv.Rmd'}
```

# OpenStreetMap

```{r child = '/../../IntroR/buildingblocks/OpenStreetMap.Rmd'}
```

# Use Case Geomedizin

```{r child = '/../../IntroR/buildingblocks/osm_geomed.Rmd'}
```

# Erste Karten

```{r child = '/../../IntroR/buildingblocks/maptools.Rmd'}
```

# Geokodierung

```{r child = '/../../IntroR/buildingblocks/geotools.Rmd'}
```

# Shapefiles bekommen, bearbeiten und visualisieren

```{r child = '/../../IntroR/buildingblocks/shapefiles_geomed.Rmd'}
```

# Interaktive Karten erstellen

```{r child = '/../../IntroR/buildingblocks/leaflet_package.Rmd'}
```

<!--
https://link.springer.com/article/10.1007/s00103-017-2647-1
http://jiscg3.blogspot.com/2011/08/open-geo-health-workshop.html

https://www.uni-trier.de/fileadmin/fb6/prof/RAU/Lehre/PPT_Humangeo/Humangeographie-Geomedizin.pdf
https://www.aerzteblatt.de/archiv/81025/Medizinische-Geografie-Der-raeumliche-Blick-auf-Gesundheit

https://de.wikipedia.org/wiki/Medizinische_Geographie

http://docplayer.org/9658463-Geographie-machen-studium-theorie-geomedizin-medizin-leben.html

OpenStreetMap + geohealth + r-project

http://jiscg3.blogspot.com/2011/08/open-geo-health-workshop.html

http://geoawesomeness.com/page/37/?m=0
-->